#include <iostream>
#include <SFML/Graphics.hpp>
#include "Bala.h"
#include "Platino.h"
#include "Jugador.h"
#include <vector>
#include <string>
using namespace sf;

int H=17;
int W=864;
int main() {

    // recorrido
    String TileMap1[H] = {
"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"r                                                                                                                                                                                                                                                       b                                                                                                                                                                           b                                                                                                                                                                                               b                                                                                                                                                                                                                                                         r",
"r                 w                                                                                     w                                                            bbbbbbbbbbb                                                                   bbbbbbbbbbb                                           w                               w                                                                                            b                                                     bbbb                                                                                                                                   b                             w                                              w                                                                                                                                                                             r",
"r                                        w                                                                                                                           b         b                                                                   b         b                                                           k                                                                                                              b                                                  b    b                         t0                                       kkkkkk                                                         b                                                                                                   r           r   rrrrrrrrr  rrrrrrrrr     rrr rrrrrrrrr                                                                                                  r",
"r                                                                                   kk                                                                               b         b                                                                   bbbbbbbbbbb                                                                                                                                               b                            b                                               b      b                        00                                                                                                     b                  k            w                  t0                          w                     r r       r r   r          r        r     r  r       r                                                                                                  r",
"r                                                                                  k  k    k k                                                                       b         b                                                                                                                                                                                                                            b b                             b                                            b        b                       00                                                                                                    b                 k                                 00                                                r  r     r  r   r                         r  r       r                                                                                                  r",
"r         w                                                                        c      kkkkk                          bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb         bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                           kkk                            bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb b          b b                 bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb          bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                          bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                k                bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                     r   r   r   r   r       r                                                                                                                               r",
"r                                                                       r          k       k k                          b                                                                                                                                                                    b                                                        b                                                       b         b   b                                                                                                                            b                         b                                                          k                                                                                       r    r r    r   rrrrrrrrr  rrrrrrrrr                                                                                                                    r",
"r                                             kckck                    rr          k  k   kkkkk                        b                                                                                                                                                                      b                                                      b                                                        b          b b                                   kk      kk                                                                                b                         b                                                        k                                                                                         r     r     r   r       r  r        r     r  r       r                                                                                                  r",
"r                                                                     rrr           kk     k k                                                                                                                                                kkkkkk                                                            kkk             kkk                                                                                                                                kk                                                                                    bbbbbbbb         bbbbbbbbbb                                                      k                                                                                           r           r   r       r  r         r    r  r       r                                                                                                  r",
"r                    kckck                                           rrrr                                                                              kkkkkkkkkkkkkkkkckkkkkkkkkkkkkkkkk                                           kkkkkk                                                                                                                                                                                                                       kk  kk                                                                                                                                                                 k                                                                                             r           r   r       r  r          r   r  r       r         r                                                                                        r",
"r                                      t0                           rrrrr                                           b                                                                                                     kkkkkk                                                                 b                                                b                                                                                                                kk                                                         t0                                                                                                      k                                     kkkckkkckkkckkkckkk                                       r           r   r       r  r           r rrr rrrrrrrrr         r                                    t0                              t0                  r",
"r                                      00              t0          rrrrrr                                t0        b                                                                                             kkkkkk                                                                           b                                              b                            t0                              b                                                kk      kk                                                     00                                                                                                    k                                                                                                                                                                                                     00                              00                  r",
"r                                      00              00         rrrrrrr                                00       b                                                                                                                                                                                b                                            b                             00                              b                                                                                                               00                                                                                                  k                                                                                                                                                                                                       00                              00                  r",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", };

//   Coins in this map
String TileMap2[H] = {
"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
"r                                                                                                                                                                    uuuu   uuuu                                                                                                                                         u                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r",
"r                                                                                                                                                                                                          uuu                      u  u                                                                                                                                                                                                              uuuuuuuuuu  uuuuu                                                                                                                                                                                                u   u     u    u    u                                                                                                                                                                                                  r",
"r                                                                                                                                                                                                    uuu                     u  u                   uuuuuuuuu                                                                                                                                                u                                                                                                                                                                                                                                     u                        u       u                                                                                                                                                                                   uuuuuuu               r",
"r              uuuuuuuu                                                            u                                             uuuu  uuuu     u uuuu  uuuuuuuuuuu                             uu                     u  u                                                                                             uuu                                                                                u   u                                                                                                                                                                                                                                 u                       u    u   u    u                                                               uuuuuuu    uuuuuuuu          uuuuuuu                                                                                                   r",
"r                                                                                                                                                                                                                                                   uuuuuuuuu                                                                                                                                             u    u                                                                                                     uuuuuuuuuuuuuuuuuuuuu                                                                                                     u                       u        u         u                                                            uuuuuuu    uuuuuuuu          uuuuuuu                                                                                                   r",
"r                                                                                   uu                                                                                                                                                                                                                                                                                                                         u                                                                                                                                                                                                                             u                                          u                                                              uuuuuuu    uuuuuuuu          uuuuuuu                                                     uuuuuuu                                       r",
"r                                             uuuuu                                 uu      u                                                                                                                                       uuuuuu                                                                      uuu             uuu                                                                            u         uuu                                                                                                                                                                                                               u                                         uu   uu                                                                                        uuuuuuu                                                                                                   r",
"r                                                                                   uu                                                                      uuuuuuuuuuuu   uuuuuuuuuuu                                    uuuuuu                                                                                                                                                                               u                                                                                                                                                                                                                         u                                       uuu         uuu                                                                                    uuuuuuu                                          uuuuuuu                                                  r",
"r                    uuuuu                                                                                                                                                                                                                                                                                                                                                                                     u                                                                                         uu    uu    uuu    uu   uu                                                                                                    u                                    uuuu                 uuuu                                  uuuuuuuuuuu                                  uuuuuuu                                                                                                   r",
"r                                                                                                                                                                                                                uuuuuu                                                                                                                                                                                        u                                                   uu                                                                                                                                                                u                                                                                                 uuuuuuuuuuu                                  uuuuuuu                                                                      uuuuuuu                      r",
"r                                                                                                                                                                                                                                                                                                                                                                                                              u                                                                                                                                                                                                                   u                                                                                                   uuuuuuuuuuu                                                                                                                                            r",
"r                                                        uuuuuu                                                                                                                                                                                                                                                                                                                                                u                                                                                                                                                                                                                 u                                                                                                                                                                                                                                                            r",
"r                                                                                                                                                                                                                                                                                                                                                                                                              u                                                                                                                                                                                                                                                                                                                                                                                                                                                                              r",
"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", };



    RenderWindow window(VideoMode(1600 , 900), "ACCION");
    window.setKeyRepeatEnabled(true);
    //fondo:
    Texture fondo;
    fondo.loadFromFile("imagenes/4.jpg");
    Sprite bg;
    bg.setTexture(fondo);
    bg.setPosition(0,0 );

     //Creando un zoom de la imagen completa del mapa 1120 X 1280 que mide la imagen
    View vista(FloatRect(260 , 395 , 600 , 500));
    vista.setSize( 1120 , 1280 );
    vista.zoom(0.7);


    //Define Objectos:
    Jugador jugador(Vector2f(100,300));/*
    Platino pla(Vector2f(50, 50));
    vector<Jugador> jugadorVec;*/
    sf::Texture textura;
    textura.loadFromFile("imagenes/ole.png");
    sf::Sprite sprite;
    sprite.setTexture(textura);
    sprite.setTextureRect(sf::IntRect(0,310,230,300));//(0,0,230,300)-(222,0,230,300)-(480,0,230,300)-(737,0,230,300) o (0,-10,230,300) abajo
    // (222,310,230,300)-(0,310,230,300)-
    sprite.move(300,450);
    sf::Vector2f centro;

    centro.x =sprite.getTextureRect().width/2.f;
    centro.y =sprite.getTextureRect().height/2.f;
    sprite.setOrigin(centro);

   // pla.setPos(Vector2f(500, 100));

    bool isFiring = false;
    int dis=100;
    //Main :
    while (window.isOpen()) {

        Event Event;
       // screen scrolling
        window.setView(vista);
        vista.setCenter(200.f, 100.f);
        vista.move(dis,50);

        //Event :
        while (window.pollEvent(Event)) {
            switch (Event.type) {

            case Event::Closed:
                window.close();
            }

            int moveSpeed = 6;

            if (Keyboard::isKeyPressed(Keyboard::Up)) {
                jugador.move(Vector2f(0, -moveSpeed));
            } else if (Keyboard::isKeyPressed(Keyboard::Down)) {
                jugador.move(Vector2f(0, moveSpeed));
            } else if (Keyboard::isKeyPressed(Keyboard::Left)) {
                jugador.move(Vector2f(-moveSpeed, 0));
            } else if (Keyboard::isKeyPressed(Keyboard::Right)) {
                jugador.move(sf::Vector2f(moveSpeed, 0));
                dis = dis + 4;
            }

            //if (Keyboard::isKeyPressed(Keyboard::Space)) {
                //isFiring = true;
            //}

        }

       window.clear();
        for(int i =0;i<100;i++)

        //for (int i = 0; i < jugadorVec.size(); i++) {
            //pla.colicion(jugadorVec[i]);

        //}


        jugador.draw(window);
        sprite.setPosition(234,100);
        //pla.draw(window);
        window.display();
    }
}
